name = "Azar"
license = "MIT"
licenselink = "https://github.com/negah/azar/blob/master/LICENSE"
description = ""
homepage = "http://negah.github.io/azar"
tags = ["simple"]
features = []
min_version = "0.41"

[author]
  name = "Dariush Abbasi"
  homepage = "https://dariush.in"
