baseURL = "/"
googleAnalytics = ""
theme = "azar"
title = "Azar"
DefaultContentLanguage = "en"
[params]
description = "fun theme."
logo = "/img/logo-mini.png"

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"

[languages]
[languages.en]
lang = "en"
languageName = "English"
weight = 1
