baseURL = "https://negah365.ir"
googleAnalytics = ""
theme = "azar"
title = "Negah"
[params]
description = "little fun projects."
logo = "/img/logo.png"

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"
