baseURL = "https://negah365.ir/azar"
googleAnalytics = ""
theme = "azar"
title = "Azar"
[params]
description = "fun theme."
logo = "/img/logo-mini.png"

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"
